#include "pwm.h"
#include "LPC17xx.h"
#include "PIN_LPC17xx.h"

void PWM_init()
{
	LPC_SC->PCONP |= (1<<6);
	LPC_SC->PCLKSEL0 |= (3<<12);
	PIN_Configure(PWM1_PORT, PWM1_PIN, PIN_FUNC_1, PIN_PINMODE_PULLDOWN, PIN_PINMODE_NORMAL);
	PIN_Configure(PWM2_PORT, PWM2_PIN, PIN_FUNC_1, PIN_PINMODE_PULLDOWN, PIN_PINMODE_NORMAL);
	PIN_Configure(PWM3_PORT, PWM3_PIN, PIN_FUNC_1, PIN_PINMODE_PULLDOWN, PIN_PINMODE_NORMAL);
	PIN_Configure(PWM4_PORT, PWM4_PIN, PIN_FUNC_1, PIN_PINMODE_PULLDOWN, PIN_PINMODE_NORMAL);

	//LPC_PWM1->PCR;
	
	return;
}