############## by W.ch
FILENAME=SPEED341
EXENAME=SPEED341
CPP=cl.exe
OUTDIR=.
INTDIR=.
ALL : $(OUTDIR)/$(EXENAME).EXE
CPP_PROJ=/nologo /MT /W3 /GX- /O2 /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D\
 "_X86_" /Fo$(INTDIR)/$(FILENAME).OBJ /c 
CPP_OBJS=./
LINK32=link.exe
LINK32_FLAGS=kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib\
 advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib\
 odbccp32.lib version.lib setupapi.lib CH341DLL.LIB\
 /NOLOGO /SUBSYSTEM:console /INCREMENTAL:no /MACHINE:IX86\
 /LIBPATH:$(DDKLIB)\i386\free \
 /OUT:$(OUTDIR)/$(EXENAME).EXE 
LINK32_OBJS= $(INTDIR)/$(FILENAME).OBJ 
$(OUTDIR)/$(EXENAME).EXE : $(OUTDIR)  $(LINK32_OBJS)
    $(LINK32) @<<
  $(LINK32_FLAGS) $(LINK32_OBJS)
<<
.c{$(CPP_OBJS)}.OBJ:
   $(CPP) $(CPP_PROJ) $<  
SOURCE=.\$(FILENAME).C
$(INTDIR)/$(FILENAME).OBJ :  $(SOURCE)  $(INTDIR)
